# Generated by Django 3.0.3 on 2020-06-06 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_shiippingaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiippingAddress',
            new_name='ShippingAddress',
        ),
    ]
